### ISSUE TITLE
[Feature Request] Add search restriction to only safehouses

### ISSUE THREAD

**Issue by R4to0** [TheCrimsonKing92/pz-item-searcher#10]
Hello, first thanks a lot for this mod!

I would like to ask if it is possible to restrict a search specifically to the safehouse area the player is in as this would be useful for multiplayer and dedicated servers so it won't get too overpowered if searching elsewhere, perhaps with a setting to toggle this on/off.

**Comment by TheCrimsonKing92** [comment]
Howdy there @R4to0-- I'm pleased that you enjoy the mod, and thanks for the feature suggestion! I like the idea and I'm sure many will find it useful, so I will look into how to interact with defined safehouses.

Currently Item Searcher defines a minimal custom UI for its search panel and doesn't do anything special for administrators, so this feature will also take a little more infrastructure work to accomplish (in a way which doesn't tromp on other mods or their UIs).

**Comment by TheCrimsonKing92** [comment]
SandboxVars is probably the appropriate place to hold this; only admins can change these values on a multiplayer server. Create a "Restrict Search to Safehouse" boolean SandboxVar, assign a default value, and read the value when attempting to search.

**Comment by TheCrimsonKing92** [comment]
@R4to0 I'm thinking there should be some gradient to this feature, along the lines of:
* Restricted - Player can search only within their safehouse, nowhere else
* Hybrid - Player can search within their safehouse or non-safehouse buildings
* Unrestricted - Player can search anywhere, even within someone else's safehouse

What do you think of that model?

**Comment by TheCrimsonKing92** [comment]
This feature is published as of v7 this morning.

**Comment by R4to0** [comment]
Sorry, I missed your previous message. I didn't got a notification for it.

Sounds good doing this way, you nailed it! Thank you!
